import Head from 'next/head'
import { Footer } from "../footer";
import { Sidebar } from "../navbar";

export const BaseLayout = ({ children }) => (
  <div className="min-h-full flex flex-col h-screen">
    <Head>
      <title>Threadly</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Sidebar />
    <main className="h-full">
      { children }
    </main> 
    <Footer />
  </div>
)
