import Head from 'next/head'
import { ToastContainer } from 'react-toastify';
import { Footer } from "../footer";
import { Sidebar } from "../navbar";
import 'react-toastify/dist/ReactToastify.css';

export const BaseLayout = ({ children }) => (
  <div className="min-h-full flex flex-col h-screen">
    <Head>
      <title>Threadly</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="shortcut icon" href="/favicon32x32.ico" type="image/x-icon" />
    </Head>
    <Sidebar />
    <ToastContainer
      closeOnClick={false}
    />
    <main className="h-full">
      { children }
    </main> 
    <Footer />
  </div>
)
